services:
  ovai:
    image: ${IMAGE_HUB-ghcr.io/prantlf/}ovai
    # environment:
    #   DEBUG: ovai,ovai:*
    ports:
      - 22434:22434
    volumes:
      - ./google-account.json:/google-account.json
      # - ./model-defaults.json:/model-defaults.json
    healthcheck:
      test: ["CMD", "/healthchk", "-m", "HEAD", "http://localhost:22434/api/ping"]
      interval: 60s
      timeout: 20s
      start_period: 20s
      # start_interval: 2s
      retries: 3
    restart: unless-stopped
